# MMLU_Pro
MMLU_PRO = {
    "biology": "These questions describe conceptual and explanatory biology problems—often open-ended—that require understanding and articulating core mechanisms in genetics, evolution, plant and animal physiology, and endocrinology, including designing experiments, evaluating competing theories, and explaining how specific structures or processes produce observed biological phenomena.",
    "history": "These questions describe analytical reasoning tasks in the social and natural sciences that require interpreting historical documents, applying comparative historical analysis, and using scientific or anthropological evidence to infer causes, processes, and timelines.",
    "chemistry": "These questions describe quantitative physical chemistry and thermodynamics problems that involve applying ideal and non-ideal gas laws, the first law of thermodynamics, electrochemical cell equations, and entropy and work relations to compute thermodynamic state variables and energy changes under specified conditions.",
    "psychology": "These questions describe behavioral science and applied statistics problems that combine perception and learning theory from psychology, basic quantitative data analysis, and practical concepts from human motivation and organizational behavior, requiring both numerical computation and conceptual explanation of human behavior and individual differences.",
    "economics": "These questions describe analytical economics problems that test understanding of macroeconomic measurement, short-run economic fluctuations, microeconomic price determination, econometric estimation in simultaneous systems, and profit-maximizing behavior under perfect competition.",
    "other": "These questions describe mixed-domain factual and applied reasoning problems that assess general knowledge in religion, biology, civics, corporate taxation, and finance through direct recall and straightforward quantitative computation.",
    "math": "These questions describe quantitative mathematics exercises—ranging from combinatorics and basic arithmetic to calculus and linear algebra—that require explicit calculation of numerical values or function outputs from given data.",
    "philosophy": "These questions describe conceptual humanities problems that test knowledge of classical philosophy, ancient history, religious thought, and formal logic through identification, interpretation, and factual recall.",
    "engineering": "These questions describe advanced, calculation-based engineering and applied mathematics problems that require applying core physical laws and standard analytical formulas to idealized systems in order to compute precise numerical results.",
    "health": "These questions describe medical and public health multiple-choice problems that require applying clinical reasoning, physiology, biochemistry, epidemiology, and nutrition principles to diagnose conditions, predict complications, interpret population health measures, and identify nutrient functions and risk factors.",
    "business": "These questions describe practical business mathematics and quantitative word problems involving percentages, simple interest, cost minimization, and installment financing, all requiring straightforward algebraic setup and numerical calculation.",
    "physics": "These questions describe quantitative physics problems that use fundamental principles—from optics, mechanics, electromagnetism, and nuclear physics—to compute specific physical quantities in idealized setups using given numerical data.",
    "law": "These questions describe law school–style hypotheticals that require applying legal doctrines from constitutional law, property, evidence, and criminal law to fact patterns in order to predict the most likely judicial or prosecutorial outcome.",
    "computer science": "These questions describe foundational computer science and engineering concepts spanning data communications, operating systems, algorithms, digital image processing, and machine learning, requiring conceptual understanding, comparative reasoning, and basic analytical evaluation of system properties and computational methods."
}


# SuperGPQA
SUPER_GPQA = {
    "Management": "These questions describe conceptual and policy-oriented social science problems focused on public administration, health policy, human capital theory, social welfare systems, and international marketing strategy, requiring classification, principle identification, and applied theoretical understanding rather than numerical computation.",
    "Literature and Arts": "These questions describe arts and humanities knowledge queries focused on music theory, literature symbolism, composers and albums, classical drama, and modern art exhibitions, requiring factual recall and interpretive understanding of artistic works and creators.",
    "Military Science": "These questions describe fact-based military science and defense studies inquiries focused on the history of military thought, senior command appointments, key revolutionary military doctrines, organizational terminology, and leadership succession in national defense systems.",
    "Agronomy": "These questions describe fact-based and applied problems in animal science, botany, forestry, and veterinary medicine that require biological classification, ecological data recall, anatomical knowledge, and clinical diagnostic reasoning for livestock diseases.",
    "Science": "These questions describe advanced quantitative science and mathematics problems—spanning astrophysics, physical chemistry equilibrium, differential equations/curve construction, real analysis of function sequences, and planetary dynamics—that require applying formal models and formulas to idealized systems in order to derive specific numerical values or rigorously characterize mathematical behavior.",
    "Economics": "These questions describe quantitative and analytical economics/business problems that combine logical argument evaluation, macroeconomic multipliers, Marxist political economy concepts, cost/benefit evaluation, and discounted cash-flow investment appraisal.",
    "Philosophy": "These questions describe comparative and interpretive philosophy, religion, and intellectual history inquiries that analyze major Western and Chinese thinkers’ views on ethics, causality, personhood, aesthetics, and religious movements, requiring conceptual understanding of philosophical doctrines and their historical contexts.",
    "Law": "These questions describe legal and political knowledge problems that require understanding of military law, civil procedure and jurisdiction, conflict-of-laws principles, and twentieth-century East Asian political history and strategy, combining doctrinal legal analysis with historical–political interpretation.",
    "Sociology": "These questions describe fact-based and conceptual sociology and social history inquiries that combine cultural anthropology, social theory, civic movements, and institutional history, requiring precise recall of dates, organizations, and definitions of core sociological concepts.",
    "History": "These questions describe fact-based historical and political knowledge queries that require precise recall of dates, official appointments, territorial definitions, foundational events, and ideological interpretations from modern and premodern history.",
    "Education": "These questions describe education and sports science theory problems that focus on student character development, exercise physiology, physical education teaching methodology, training control principles, and learner-centered instructional design, requiring conceptual understanding of how physiological factors and pedagogical strategies influence student learning and development.",
    "Medicine": "These questions describe applied medical and biomedical science problems that require integrating physiology, pathology, pharmacokinetics, and immunohematology to identify disease mechanisms, interpret clinical signs, and explain diagnostic or treatment-related phenomena.",
    "Engineering": "These questions describe technical and applied science problems spanning marine instrumentation, mechanical engineering materials, medical aesthetics technology, information theory coding efficiency, and strategic geophysical sensing, requiring domain-specific technical knowledge and practical reasoning.",
}

# MedMCQA
MEDMCQA = {
    "Pathology": "These questions describe applied medical pathology and genetic risk assessment problems that require understanding of endocrine dysfunction in systemic disease, characteristic histopathological tissue injury patterns, premalignant lesion progression, Mendelian inheritance probabilities, and the fundamental pathological changes associated with chronic metabolic disorders.", 
    "Ophthalmology": "These questions describe applied ophthalmology and orbital anatomy knowledge checks that test identification of extraocular muscle anatomy, patterns of orbital trauma, infectious causes of pediatric eye disease, vascular causes of proptosis, and precise anatomical relationships within the lacrimal drainage system.",
    "Gynaecology & Obstetrics": "These questions describe applied obstetrics and reproductive physiology knowledge checks that focus on abnormal pregnancy types, statistical laws of multiple gestation, placental disorders, timing of ovulation, and the appropriate gestational age for prenatal diagnostic procedures.", 
    "Anaesthesia": "These questions describe applied anesthesiology and perioperative medicine problems that test understanding of anesthesia physiology, emergency induction drug selection, anesthetic equipment function, neuromuscular pharmacology, and respiratory support principles such as CPAP.", 
    "Forensic Medicine": "These questions describe applied community medicine, forensic medicine, and clinical toxicology problems that require understanding of safe substance use limits, postmortem changes, principles of enhanced drug elimination, identification of common environmental poisons, and recognition of characteristic clinical signs of heavy-metal toxicity.", 
    "Psychiatry": "These questions describe clinical psychiatry, neurology, pharmacology, and behavioral psychology problems that assess recognition of substance-related emergencies, rational drug selection in children, principles of learning and reinforcement, EEG interpretation, and mood disorder diagnosis.", 
    "Unknown": "These questions describe integrated medical science knowledge checks spanning endocrinology, infectious disease diagnostics, pediatric emergency medicine, neuroanatomy of sensory pathways, and biostatistics, requiring applied understanding of disease mechanisms, clinical presentation and management, physiological pathways, and research methodology.", 
    "Microbiology": "These questions describe core medical microbiology and immunology knowledge checks that focus on immune protein synthesis, host–parasite relationships, bacterial virulence factors, laboratory identification of pathogens based on culture characteristics, and fundamental biological classification of fungi.", 
    "Medicine": "These questions describe integrated clinical medicine knowledge checks that require applying anatomy, cardiology diagnostics, immunology, hematology, and electrocardiography principles to identify disease mechanisms, diagnostic tests, and characteristic clinical findings.", 
    "Radiology": "These questions describe diagnostic radiology and medical imaging knowledge problems that assess understanding of MRI and CT principles, radiographic anatomy and pathology correlations, systemic disease indicators on imaging, and safe imaging practices in pregnancy.", 
    "Biochemistry": "These questions describe core biochemistry and molecular biology knowledge checks that require understanding of lipid metabolism, RNA processing, ketone body synthesis, metabolic pathway integration, and hormone storage physiology.", 
    "Dental": "These questions describe foundational dental and oral pathology knowledge checks that assess understanding of oral histology, mucocutaneous disease identification, pediatric orthodontic appliances, diagnostic criteria, and periodontal tissue healing mechanisms.", 
    "Pediatrics": "These questions describe core pediatrics and neonatal medicine knowledge checks that focus on infant and child physiology, developmental milestones, neonatal pathology, congenital cardiovascular adaptation, toxic ingestion emergencies, and bilirubin metabolism–related risks, requiring applied clinical understanding of normal development and common pediatric disorders.", 
    "Physiology": "These questions describe core human physiology and biomedical science knowledge checks that focus on hormone secretion, cardiac electrophysiology, intracellular second-messenger systems, membrane biophysics, and gastrointestinal motility patterns, requiring integrated understanding of cellular signaling and organ system function.", 
    "Skin": "These questions describe clinical dermatology multiple-choice problems that assess recognition of skin disease patterns, drug-related complications, characteristic pathological phenomena, pregnancy-related treatment considerations, and the mechanisms and management of pigmentary and pustular dermatoses.", 
    "Pharmacology": "These questions describe applied clinical pharmacology and emergency medicine knowledge checks that focus on drug mechanisms of action, receptor physiology, antidote use in poisoning, obstetric therapeutics, dermatologic treatments, and antibiotic modes of action for rational clinical decision-making.", 
    "Social & Preventive Medicine": "These questions describe applied epidemiology, infectious disease control, and biostatistics problems that focus on disease surveillance, transmission dynamics, risk measurement, standardized treatment regimens, and interpretation of temporal patterns in public health data.", 
    "ENT": "These questions describe applied ENT and neuroanatomy knowledge problems that require understanding of cranial nerve injury effects, auditory and visual sensory physiology, tympanic membrane histology, cholesteatoma pathology, and characteristic fracture patterns of the facial skeleton.", 
    "Surgery": "These questions describe applied clinical medicine and surgery knowledge checks that focus on cancer patterns, anatomical risk during operative procedures, characteristic diagnostic signs, common causes of acute surgical emergencies, and evidence-based hormonal therapy selection.", 
    "Orthopaedics": "These questions describe orthopedic clinical knowledge problems that test diagnosis, deformity identification, fracture management principles, bone infection etiology, and classic fracture–dislocation patterns through applied medical reasoning.", 
    "Anatomy": "These questions describe foundational human anatomy knowledge checks that test structural identification, embryological origin of muscles, composition of superficial tissues, and key anatomical relationships between organs and neurovascular structures."
}

# BBEH
BBEH = {
    "bbeh_geometric_shapes": "This question type tests planar and computational geometry reasoning from low-level graphical data: the student is given an SVG path consisting of M/L coordinate pairs that define multiple line segments in the plane, must mentally reconstruct the composite drawing formed by those segments, account for collinearity where multiple segments form a single side, and then identify which polygonal shapes are present from a fixed taxonomy (triangles, rectangles, squares, trapezoids, parallelograms, and various classes of pentagons and hexagons), using geometric properties such as number of sides, parallelism, right angles, regular vs irregular structure, and convexity vs concavity.", 
    "bbeh_movie_recommendation": "These ten problems are all the same general type: for each question, you are (implicitly) given some candidate options, where each option is a set or pair/list of movies, and your task is to decide which option contains movies that are most similar with respect to how a group of people will respond to them—that is, which option groups together movies that are likely to be liked or disliked by (roughly) the same subset of people; solving each item requires comparing, across the options, the predicted preference patterns for the movies in that option (e.g., genre overlap, tone, target audience, prior ratings or response profiles) and then selecting the option whose movies have the highest expected alignment in group-level like/dislike outcomes.", 
    "bbeh_boolean_expressions": "These ten problems are classic self-referential logic puzzles of the “exactly one statement is true” form: for each question you are given five candidate expressions (not shown here), and you must determine which single one can consistently be true under the global constraint that the other four are false; solving them requires systematically exploring the logical relations among the five expressions in each set (often involving mutual reference, counting claims like “exactly two of these are true/false,” or structural dependencies), identifying contradictions that arise if you assume each candidate is the true one in turn, and finding the unique assignment of truth values that satisfies the constraint for each question independently.",
    "bbeh_shuffled_objects": "This question tests long-horizon state tracking and update reasoning in a dynamic system: the student is given an initial configuration of entities and their associated states (such as positions, partners, gifts, or objects), followed by an extremely long sequence of pairwise swap actions interspersed with null events and irrelevant discussions, and must deterministically simulate the effects of these operations to determine the final state of a queried variable. Correctly solving it requires precise bookkeeping of swaps, recognizing that repeated swaps undo previous ones, ignoring non-state-changing actions, maintaining consistency across hundreds of transitions, and extracting the final ownership, location, or partner of a specified individual.", 
    "bbeh_nycc": "This question tests pragmatic and stylistic judgment in evaluating humor: given short descriptions of New Yorker–style cartoons and multiple candidate captions (not shown here), the student must imagine the scene, infer the likely social context and character attitudes, and then choose the caption whose wording, tone, and perspective produce the strongest comic effect, taking into account incongruity, timing, voice, and how well the caption fits the visual details and implied narrative.", 
    "bbeh_causal_understanding": "This question tests long-horizon state tracking and update reasoning in a dynamic system: the student is given an initial configuration of entities and their associated states (such as positions, partners, gifts, or objects), followed by an extremely long sequence of pairwise swap actions interspersed with null events and irrelevant discussions, and must deterministically simulate the effects of these operations to determine the final state of a queried variable. Correctly solving it requires precise bookkeeping of swaps, recognizing that repeated swaps undo previous ones, ignoring non-state-changing actions, maintaining consistency across hundreds of transitions, and extracting the final ownership, location, or partner of a specified individual.", 
    "bbeh_hyperbaton": "Question tests understanding and induction of adjective ordering constraints in a specific artificial variant of English: the student is given a large list of noun phrases whose adjective order is stipulated to be well-formed in that variant, must infer the underlying hierarchy or template governing semantic classes of modifiers (e.g., evaluative, size, age, color, material, nationality, activity-related/participial, shape, etc.), and then apply the inferred ordering rules to a new set of candidate noun phrases (Options A–J) to decide which have a grammatical adjective sequence in that system, including cases with multiple adjectives, mixed semantic types, and interaction of lexicalized participles with more canonical adjectives.", 
    "bbeh_boardgame_qa": "This question tests rule-based nonmonotonic logical reasoning in a toy narrative “boardgame” domain: the student is given an initial set of facts about many agents (animals) plus a large collection of conditional rules, some of which are defeasible and explicitly ordered by preferences, and must compute whether a target query (e.g., “does X do Y?”) is provably true, provably false, or remains undecided. Solving it requires forward-chaining through the rules, tracking derived literals, handling multi-premise antecedents, reasoning about existence statements (“there exists an animal that…”), and crucially resolving conflicts when different rules support a proposition and its negation by respecting the given priority relation over rules, thereby determining whether the queried statement is classified as proved, disproved, or unknown.", 
    "bbeh_disambiguation_qa": "This question tests discourse-level pronoun resolution and coreference reasoning in natural language: the student is given short multi-clause narratives containing multiple pronouns whose antecedents may be explicit, implicit, or genuinely ambiguous, and must determine which entities each pronoun refers to by using grammatical cues (gender, number, syntactic role), semantic plausibility, discourse coherence, and pragmatic context, including cases with conflicting gender stereotypes, shifting speakers, plural references, and long-distance dependencies across sentences."
}
